name: 📝 Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["📝 documentation", "🔍 status: needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please fill out the information below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated documentation
        - Unclear/confusing documentation
        - Typo or formatting issue
        - Code example needed
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue? (File path, URL, or section name)
      placeholder: e.g., README.md, docs/API.md, Section "Getting Started"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (If applicable)
      placeholder: Copy the current text or describe what's there now

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What's wrong or missing?
      placeholder: Describe the issue with the current documentation
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: How should it be fixed or what should be added?
      placeholder: Provide suggested text, structure, or examples
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which component is this documentation about?
      multiple: true
      options:
        - General/Repository
        - Backend/API
        - Admin Panel
        - Mobile App
        - Shared Package
        - Installation/Setup
        - Configuration
        - Deployment
        - Contributing Guide
        - Other

  - type: textarea
    id: audience
    attributes:
      label: Target Audience
      description: Who is this documentation for?
      placeholder: e.g., New contributors, end users, developers, system administrators
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please confirm the following
      options:
        - label: I have checked that this documentation issue hasn't been reported before
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I am willing to submit a pull request to fix this documentation
          required: false
