name: ❓ Question
description: Ask a question about YektaYar
title: "[Question]: "
labels: ["❓ question", "🔍 status: needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much detail as possible.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation/Setup
        - Configuration
        - Usage/How-to
        - Architecture/Design
        - Best Practices
        - Troubleshooting
        - Contributing
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which component is your question about?
      multiple: true
      options:
        - General
        - Backend/API
        - Admin Panel
        - Mobile App
        - Shared Package
        - Database
        - Deployment
        - Documentation
        - Other

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information
      placeholder: |
        What are you trying to accomplish?
        What have you already tried?
        Any relevant code or configuration?

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Provide environment details if relevant to your question
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 13]
        - Node.js Version: [e.g., 20.10.0]
        - Package Version: [e.g., 1.0.0]
      value: |
        - OS: 
        - Node.js Version: 
        - Package Version: 

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information that might be helpful
      placeholder: Screenshots, error messages, code snippets, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the documentation
          required: true
        - label: I have provided all relevant information
          required: true
